* Why
  :PROPERTIES:
  :CUSTOM_ID: why
  :END:

LWN.net has a lot of really well-written articles, and I've been
collating some great articles for people at different skill levels. The
initial inspiration for this was to find articles for an operating
systems class I was tutoring.

** Introductory Articles
   :PROPERTIES:
   :CUSTOM_ID: introductory-articles
   :END:

-  [[https://lwn.net/Articles/250967/][Ulrich Drepper's 7-part series on
   what every programmer should know about memory]]

** Intermediate-Level
   :PROPERTIES:
   :CUSTOM_ID: intermediate-level
   :END:

-  [[https://lwn.net/Articles/749064/][Variable-length arrays, pros and
   cons]]
-  [[https://lwn.net/Articles/374424/%5D][What if we we used really
   large pages (> 1 MB) versus the smaller page sizes that we normally
   use?]]
-  [[https://lwn.net/Articles/767137/][How can we get more fine-grained
   security than just having read/write/execute permissions for files?
   Could we restrict particular applications to only access certain
   directories?]]. See also: the pledge() syscall.
-  [[https://lwn.net/Articles/615809/][System calls are slow since we
   need to switch to the OS: can we allow certain syscalls to be
   implemented in user-space memory? (vDSO)]]
-  [[https://lwn.net/Articles/631631/][How does a program get run?]]
