* Paper Review
  :PROPERTIES:
  :CUSTOM_ID: paper-review
  :END:

The point of "Paper Review" is to summarize research articles I found
interesting. To that end, these reviews will start with an
oversimplified abstract, then break down the premises and contributions
of the paper, and finally go in-depth into topics found in the paper.
While these were initially written to aid my own understanding of the
research, hopefully they'll be both enlightening and cater to whatever
depth-of-interest you might be into.

** Questions for any research paper
   :PROPERTIES:
   :CUSTOM_ID: questions-for-any-research-paper
   :END:

1. What is the problem that the paper is trying to solve? Why is it
   important?
2. To solve the problem, a good paper must provide an insightful
   observation that eventually would lead to the solution. What's the
   most important observation that this paper makes?
3. What's the proposed solution? How does the paper leverage the above
   insight to devise the solution?
4. What are the advantages of the solution?
5. What are the disadvantages of the proposed solution? How would you
   improve this work to avoid the disadvantages?

Thank you to Assistant Professor Djordje Jevdjic from NUS for this
framework.
